server:
  port: 8080                              # 端口号
  tomcat:
    connection-timeout: 5000ms            # 连接超时时长（毫秒）
    uri-encoding: UTF-8                   # uri 格式
  servlet:
    context-path: /api                    # 请求前缀

spring:
  jackson:
    time-zone: GMT+8                      # 时区
    date-format: yyyy-MM-dd HH:mm:ss      # 时间格式 (Date生效, LocalDateTime不生效)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weapp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456                             # 密码(默认为空)
    timeout: 6000ms                              # 连接超时时长(毫秒)

mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml    # Mapping 存放位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # sql 日志打印
  type-aliases-package: com.zxiaosi.backend.domain
  # https://baomidou.com/pages/56bac0/#globalconfig-2
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增", input:"用户输入ID", assign_id:"全局唯一ID (数字类型唯一ID)", assign_uuid:"全局唯一ID UUID";
      id-type: auto
      logic-delete-field: 1                       # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0                   # 逻辑未删除值(默认为 0)
      table-underline: true                       # 表名是否使用驼峰转下划线命名,只对表名生效

config:
  weixin:
    appid: 'touristappid'
    secret: 'touristappid12345678912345678912'
  jwt:
    secret: '2159cslsknjgvehr'
    expire: '86400'                               # 24 * 60 * 60
    header: 'Authorization'
  redis:
    default-expire: '86400'                               # 24 * 60 * 60
    not-expire: '86400'                               # 24 * 60 * 60